name: vboxstock

services:
  vboxstock:
    image: ghcr.io/mfwadejr/vboxstock:latest
    container_name: vboxstock
    restart: unless-stopped
    ports:
      - "8269:3000"
    volumes:
      - ./data:/data
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
